language: python

env:
  global:
    - R_LIBS_USER=~/R _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=false
  matrix:
# matrix-start
    - R_CHECK_PACKAGES=""
# matrix-end

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get -qq update
  - "yes | sudo apt-get -qq upgrade"
  - sudo apt-get -qq install r-base-dev r-cran-devtools texinfo > /dev/null
  - sudo apt-get autoremove
  - "[ ! -d ${R_LIBS_USER} ] && mkdir ${R_LIBS_USER}"

script:
  - Rscript cran-check.R
