language: java

jdk:
  - openjdk7

env:
  global:
    - R_LIBS_USER=~/R _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=false RSTUDIO_PANDOC=/usr/lib/rstudio/bin/pandoc
  matrix:
# matrix-start
    - R_CHECK_PACKAGES=""
# matrix-end

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get -qq update
  - sudo apt-get -qq install r-base-dev texinfo > /dev/null
  - sudo apt-get autoremove
  - "[ ! -d ${R_LIBS_USER} ] && mkdir ${R_LIBS_USER}"
  - sudo R CMD javareconf

script:
  - rm -rf travis_done
  - "Rscript cran-check.R 2>&1 | tee travis_out && echo 0 > travis_done || touch travis_done &"
  - sleep 5
  - "while [ ! -e travis_done ]; do sleep 30; rm travis_out 2> /dev/null || echo .; done"
  - "[ -s travis_done ] || exit 1"
